version: '3.8'
services:
  monitor:
    build: .
    container_name: attack_surface_monitor
    volumes:
      - ./src:/app/src
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "src/main.py", "--help"]
